### ISSUE TITLE
Programme TV non fonctionnel

### ISSUE THREAD

**Issue by azertigrou** [byackee/jarvis-progtv#1]
Impossible de récupérer le programme TV:
 jarvis: le programme de ce soir sur la deux est
Error: no "print" mailcap rules found for type "inode/directory"

Meme chose sur toutes les chaines

**Comment by byackee** [comment]
Bonjour,

Je n'ai pas rencontré cette erreur, peux tu me dire si le fichier tnt.xml est présent dans le répertoire plugins/jarvis-progtv ?

**Comment by byackee** [comment]
Bonjour,

J'ai fais des modifications depuis ce post surotu au niveau du téléchargement du fichier xml

**Comment by byackee** [comment]
j'ai fait beaucoup de modification depuis l'ouverture de "l'issue" et pas de retour depuis mi decembre donc je cloture
