### ISSUE TITLE
Keyborad mode ne fonctionne pas?

### ISSUE THREAD

**Issue by Xenderblade** [byackee/jarvis-progtv#2]
Bonjour, je test actuellement votre plugin et il ne reconnait pas les commande clavier que je lui indique :

moi: donne le programme télé sur la une
jarvis: Je n'ai pas compris: donne le programme télé sur la une

Commands :
```
*program*tel*sur* (*)== say "le programme de ce soir sur la (1) est " && say "$(jv_pg_pt_lunch (1))"
*TELECHARGE*PROGRAMME*TV*==jv_pg_tv_download
```

j'ai bien le fichier tnt
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">

<tv source-info-url="http://guidetv-iphone.telerama.fr" source-data-url="http://guidetv-iphone.telerama.fr" generator-info-name="XMLTV" generator-info-url="http://mythtv-fr.org/">
  <channel id="C1.telerama.fr">
    <display-name>TF1</display-name>
    <icon src="http://localhost/logo1.gif" />
  </channel>
  <channel id="C2.telerama.fr">
    <display-name>France 2</display-name>
    <icon src="http://localhost/logo2.gif" />
  </channel>
.....
......
```

Le fichier config.sh :
```
pourquand='{ "devices":[
{ "voiciladate": "C1.telerama.fr", "nom": "une"},
{ "voiciladate": "C2.telerama.fr", "nom": "deux"},
{ "voiciladate": "C3.telerama.fr", "nom": "trois"},
{ "voiciladate": "C4.telerama.fr", "nom": "quatre"},
{ "voiciladate": "C5.telerama.fr", "nom": "cinq"},
{ "voiciladate": "C6.telerama.fr", "nom": "six"}
]}'
```

**Comment by byackee** [comment]
Bonjour,

Pouvez vous me donner l'ordre de vos plugins ? vous est il possible de n'activer que ce plugin pour voir si l'erreur est toujours la?

**Comment by Xenderblade** [comment]
Bonjour,

je viens de changer l'ordre des plugin et on avance ! Par contre la réponse est vide maintenant :

> Xender: télécharge le programme tv
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 2178k  100 2178k    0     0  10.0M      0 --:--:-- --:--:-- --:--:-- 10.1M
> Archive:  /tmp/progtv.zip
>   inflating: /home/pi/jarvis/plugins/jarvis-progtv/tnt.xml  
> Xender: donne le programme télé sur la une
> jarvis: le programme de ce soir sur la une est 
> jarvis: 

Ordre des plugins :

> jarvis-progtv
> jarvis-time
> jarvis-ui
> jarvis-temperature
> jarvis-api
> jarvis-kodi
> fr_liveboxtv

tnt.xml est bien présent


Merci de ton aide

**Comment by byackee** [comment]
J'ai fait une modification du plugin pour qu'il ne donne que les programmes a partir de 21h et de plus de 40 mins pour n pas sortir par exemple la méteo ou autres petites émissions. 
Il doit y avoir un probleme a ce niveau la, je regarde ce soir

**Comment by byackee** [comment]
Bonjour,

Une question, as tu essayé de desinstaller et reinstaller le plugin?

**Comment by Xenderblade** [comment]
c'est bon j'ai désinstallé et réinstallé et ça fonctionne bien merci beaucoup pour ton aide !
