### ISSUE TITLE
ne marche pas

### ISSUE THREAD

**Issue by davidjr972** [byackee/jarvis-progtv#3]
bonjour
j'ai installé le plugin je n'arrive pas a le faire fonctionner
quand je lance jarvis en mode troublershouting il reconnais bien mes mots il me reponds : null

**Comment by davidjr972** [comment]
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 5 silence 1 0.1 1 1 0.5 1 trim 0 5
DEBUG: speech duration was 32 (10 = 1 sec)
DEBUG: stop_listening hook
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=e2e6e86b-943b-45a8-8150-bce6803de0ce&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"donne le programme télé ce soir sur la une","lexical":"donne le programme télé ce soir sur la une","properties":{"requestid":"c8a6fd28-2f21-4ecd-80e3-7f16e8da037d","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"donne le programme télé ce soir sur la une","lexical":"donne le programme télé ce soir sur la une","confidence":"0.7833455","properties":{"HIGHCONF":"1"}}]}
donne le programme télé ce soir sur la une
$> say "$(jv_pg_pt_lunch ${BASH_REMATCH[1]} 'cesoir' "$jv_pg_pt_duration")"

DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 5 silence 1 0.1 1 1 0.5 1 trim 0 5
DEBUG: stop_listening hook
DEBUG: timeout, end of conversation
DEBUG: listening_timeout hook
DEBUG: exiting_cmd hook
jarvis: Waiting to hear 'jarvis'

merci de votre aide

**Comment by davidjr972** [comment]
bonsoir 
j'ai réinstallé ça fontionne

**Comment by byackee** [comment]
Bonsoir,

Pas de soucis :)
